services:
  rrs-proxy-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: rrs-proxy-server:latest
    container_name: rrs-proxy-server
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    network_mode: host
