
services:
  socket-server:
    build:
      context: ../
      dockerfile: backend/Dockerfile.prod
    image: rrs-fastapi-preview:latest
    container_name: socket-server-service-preview
    environment:
      - SERVICE=socket-server
      - PORT=11337
    restart: unless-stopped
    env_file:
      - ./services/socket-server/config.env
    volumes:
      - ./services/socket-server/socket-server.arm64.bin:/socket-server.bin
    network_mode: host
    ipc: host

  manipulate:
    build:
      context: ../
      dockerfile: backend/Dockerfile.prod
    image: rrs-fastapi-preview:latest
    container_name: manipulate-service-preview
    environment:
      - SERVICE=manipulate
      - PORT=8001
    restart: unless-stopped
    env_file:
      - ./services/manipulate/config.env
    volumes:
      - ./services/manipulate/manipulate.arm64.bin:/manipulate.bin
    network_mode: host
    ipc: host

  api-gateway:
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    image: rrs-nginx:latest
    environment:
      - BUILDKIT_PROVENANCE=0
      - BUILDKIT_SBOM_SCAN=0
    container_name: api-gateway
    restart: unless-stopped
    volumes:
      - ../api-gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    network_mode: host
