[project]
name = "rb_zenoh"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
description = "Rainbow Zenoh Python"
authors = [
    { name = "Derek", email = "dfd1123@rainbow-robotics.com" }
]
readme = "README.md"

dependencies = [
    "eclipse-zenoh>=1.5.0,<1.6.0",
    "psutil>=7.0.0,<8.0.0",
    "flatbuffers>=25.2.10,<26.0.0",
]