[project]
name = "rb_zenoh"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
description = "Rainbow Zenoh Python"
authors = [
    { name = "Derek", email = "dfd1123@rainbow-robotics.com" }
]
readme = "README.md"

dependencies = [
    "psutil>=7.0.0,<8.0.0",
    "flatbuffers>=25.2.10,<26.0.0",
    "fastapi>=0.116.1",
    "rb_utils",
    "rb_modules",
]

[dependency-groups]
dev = [
    "eclipse-zenoh==1.5.0",
]

[tool.uv.sources]
rb_utils = { workspace = true }
rb_modules = { workspace = true }
