[project]
name = "rb_modbus"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
description = "Rainbow Modbus"
authors = [
    { name = "Derek", email = "dfd1123@rainbow-robotics.com" }
]
readme = "README.md"

dependencies = [
    "pymodbus>=3.8.0",
]
