[project]
name = "rb_modules"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
description = "Rainbow Modules"
authors = [
    { name = "Derek", email = "dfd1123@rainbow-robotics.com" }
]
readme = "README.md"

dependencies = [
    "psutil>=7.0.0,<8.0.0",
    "flatbuffers>=25.2.10,<26.0.0",
    "fastapi>=0.116.1",
    "utils",
    "rb_database",
    "rb_zenoh",
    "rb_socketio",
    "rb_schemas",
    "rb_resources",
    "rb_flat_buffers",
    "pydantic-settings>=2.10.1",
]

[tool.uv.sources]
utils = { workspace = true }
rb_database = { workspace = true }
rb_zenoh = { workspace = true }
rb_socketio = { workspace = true }
rb_schemas = { workspace = true }
rb_resources = { workspace = true }
rb_flat_buffers = { workspace = true }