[project]
name = "rb_schemas"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
description = "Rainbow Common Schema"
authors = [
    { name = "Derek", email = "dfd1123@rainbow-robotics.com" }
]
readme = "README.md"

dependencies = [
    "flatbuffers>=25.2.10,<26.0.0",
    "fastapi>=0.116.1",
    "rb_utils",
    "rb_flow_manager",
]

[tool.uv.sources]
rb_utils = { workspace = true }
rb_flow_manager = { workspace = true }