[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "rb_flow_manager"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
description = "Rainbow Python Flow Manager"
authors = [
    { name = "Derek", email = "dfd1123@rainbow-robotics.com" }
]
readme = "README.md"

dependencies = [
  "rb_utils",
  "rb_zenoh",
  "rb_flat_buffers",
]

[tool.uv.sources]
rb_utils = { workspace = true }
rb_zenoh = { workspace = true }
rb_flat_buffers = { workspace = true }