[project]
name = "flat_buffers"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
description = "FlatBuffers"
authors = [
    { name = "Derek", email = "dfd1123@rainbow-robotics.com" }
]

dependencies = [
    "flatbuffers>=25.2.10,<26.0.0",
    "numpy>=2.3.3",
]
