[project]
name = "rb_influxdb"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
description = "Rainbow InfluxDB"
authors = [
    { name = "Derek", email = "dfd1123@rainbow-robotics.com" }
]
readme = "README.md"

dependencies = [
    "fastapi>=0.116.1",
    "influxdb-client>=1.40.0",
    "rb_utils",
]

[tool.uv.sources]
rb_utils = { workspace = true }
