[project]
name = "utils"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
description = "Common utilities"
authors = [
    { name = "Derek", email = "dfd1123@rainbow-robotics.com" }
]

dependencies = [
    "psutil>=7.0.0,<8.0.0",
]